- name: Copy hpfeeds configuration file
  copy:
    src: hpfeeds.cfg
    dest: /data/ews/conf
    owner: nwx
    group: nwx
    mode: 0770
  register: config

- name: Applying hpfeeds settings
  command: /opt/nwx/bin/hpfeeds_optin.sh --conf=/data/ews/conf/hpfeeds.cfg
  when: config.changed == true
