# T-Pot Image Builder (use only for building docker images)
version: '2.3'

services:

##################
#### Honeypots
##################


##################
#### NSM
##################

# Fatt service
  fatt:
    build: fatt/.
    image: "us.gcr.io/neutralthreat/fatt:2006"

# P0f service
  p0f:
    build: p0f/.
    image: "us.gcr.io/neutralthreat/p0f:2006"

# Suricata service
  suricata:
    build: suricata/.
    image: "us.gcr.io/neutralthreat/suricata:2006"


##################
#### Tools
##################

#### ELK
## Elasticsearch service
  elasticsearch:
    build: elk/elasticsearch/.
    image: "us.gcr.io/neutralthreat/elasticsearch:2006"

## Kibana service
  kibana:
    build: elk/kibana/.
    image: "us.gcr.io/neutralthreat/kibana:2006"

## Logstash service
  logstash:
    build: elk/logstash/.
    image: "us.gcr.io/neutralthreat/logstash:2006"

## Elasticsearch-head service
  head:
    build: elk/head/.
    image: "us.gcr.io/neutralthreat/head:2006"
